-- Migration: add analytics, alerts, recommendations and automations tables
-- Run this on the Supabase/Postgres database used by the API

-- Analytics snapshots: periodic aggregated metrics for a farm
CREATE TABLE IF NOT EXISTS analytics_snapshots (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  fazenda_id UUID REFERENCES fazendas(id) ON DELETE CASCADE,
  total_animais INTEGER,
  animais_sem_pesagem_recente INTEGER,
  vacinacoes_pendentes INTEGER,
  rebanho_score INTEGER,
  avg_peso NUMERIC(8,2),
  payload JSONB,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_analytics_snapshots_fazenda ON analytics_snapshots (fazenda_id);

-- Alerts center
CREATE TABLE IF NOT EXISTS alerts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  fazenda_id UUID REFERENCES fazendas(id) ON DELETE CASCADE,
  tipo TEXT,
  nivel TEXT CHECK (nivel IN ('INFO','WARNING','CRITICAL')) DEFAULT 'INFO',
  titulo TEXT,
  descricao TEXT,
  data JSONB,
  lida BOOLEAN DEFAULT false,
  arquivada BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_alerts_fazenda ON alerts (fazenda_id);

-- Recommendations generated by analytics engine
CREATE TABLE IF NOT EXISTS recommendations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  fazenda_id UUID REFERENCES fazendas(id) ON DELETE CASCADE,
  prioridade INTEGER DEFAULT 3,
  motivo TEXT,
  impacto TEXT,
  payload JSONB,
  acknowledged BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_recommendations_fazenda ON recommendations (fazenda_id);

-- Automations configuration
CREATE TABLE IF NOT EXISTS automations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  fazenda_id UUID REFERENCES fazendas(id) ON DELETE CASCADE,
  nome TEXT,
  trigger JSONB,
  actions JSONB,
  enabled BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_automations_fazenda ON automations (fazenda_id);
